plot_SPC(df_name = "NHS24_Mon_Fri_AA", df = NHS24_Mon_Fri_AA, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", breakPoint = 43)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_gramp",df = NHS24_Mon_Fri_gramp, place_title = "Grampian", exclude = 18, breakPoint = 64, exclude2 = 19)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_shet",df = NHS24_Mon_Fri_shet, place_title = "Shetland")
plot_SPC(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_gramp", df = NHS24_Sat_Sun_gramp, place_title = "Grampian")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C'", df_name = "NHS24_Sat_Sun_scot", df = NHS24_Sat_Sun_scot, place_title = "Scotland")
plot_SPC(df_name = "GPOOH_Mon_Fri_fife", df = GPOOH_Mon_Fri_fife, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Fife")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_borders", df = assHub_borders, place_title = "Borders", breakPoint = 118)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_dg", df = assHub_dg, place_title = "Dumfries and Galloway", breakPoint = 56, breakPoint2 = 116)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_fife", df = assHub_fife, place_title = "Fife", breakPoint = 22)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_lan", df = assHub_lan, place_title = "Lanarkshire", breakPoint = 33, breakPoint2 = 83, breakPoint3 = 117)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_high", df = SAS_attended_high, place_title = "Highlands", breakPoint = 40)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_forthV", df = SAS_conveyed_forthV, place_title = "Forth Valley", breakPoint = 44)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_AA", df = fourHrPerf_AA, breakPoint = 24, breakPoint2 = 46, breakPoint3 = 86, breakPoint4 = 127)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_high", df = fourHrPerf_high, place_title = "Highlands", breakPoint = 36, breakPoint2 = 106)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_AA", df = fourHrPerf_AA, breakPoint = 31, breakPoint2 = 57)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_borders", df = fourHrPerf_borders, place_title = "Borders")
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_forthV", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 36)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_borders", df = selfPres_borders, place_title = "Borders", breakPoint = 22, breakPoint2 = 85, breakPoint3 = 109)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_forthV", df = selfPres_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_glow", df = selfPres_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 43, breakPoint2 = 92, breakPoint3 = 129)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_tay", df = selfPres_tay, place_title = "Tayside", breakPoint = 29, breakPoint2 = 94)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_lan", df = emerg_ad_lan, place_title = "Lanarkshire", breakPoint = 93)
