#script for graphs

plot_SPC(plot_chart = F, write_table = T, df_name = "NHS24_Mon_Fri_AA", df = NHS24_Mon_Fri_AA, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", breakPoint = 43)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_borders", df = NHS24_Mon_Fri_borders, place_title = "Borders",breakPoint = 64)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_dg",df = NHS24_Mon_Fri_dg, place_title = "Dumfries and Galloway", breakPoint = 73, exclude2 = c(11,15,16))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_fife",df = NHS24_Mon_Fri_fife, place_title = "Fife", breakPoint = 64, exclude2 = 20)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_forthV",df = NHS24_Mon_Fri_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 29, breakPoint2 = 66, exclude3 = c(18,22))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_gramp",df = NHS24_Mon_Fri_gramp, place_title = "Grampian", exclude = 18, breakPoint = 64, exclude2 = 19)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_glow",df = NHS24_Mon_Fri_glow, place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_high",df = NHS24_Mon_Fri_high, place_title = "Highlands", breakPoint = 25, exclude2 = 8, breakPoint2 = 64, exclude3 = 19)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_lan",df = NHS24_Mon_Fri_lan, place_title = "Lanarkshire", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_loth",df = NHS24_Mon_Fri_loth, place_title = "Lothian", breakPoint = 27, breakPoint2 = 64, exclude3 = 19)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_ork",df = NHS24_Mon_Fri_ork, place_title = "Orkney", exclude = 18, breakPoint = 40)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_shet",df = NHS24_Mon_Fri_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_tay",df = NHS24_Mon_Fri_tay, place_title = "Tayside", breakPoint = 64, exclude2 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_west",df = NHS24_Mon_Fri_west, place_title = "Western Isles", breakPoint = 64, exclude2 = 20)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C'", df_name = "NHS24_Mon_Fri_scot",df = NHS24_Mon_Fri_scot, place_title = "Scotland", breakPoint = 32, breakPoint2 = 64, exclude3 = 20)


plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_AA", df = NHS24_Mon_Fri_IH_AA, exclude = c(14,15), breakPoint = 45)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_borders", df = NHS24_Mon_Fri_IH_borders,place_title = "Borders", breakPoint = 66)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_dg", df = NHS24_Mon_Fri_IH_dg,place_title = "Dumfries and Galloway", breakPoint = 33, breakPoint2 = 66, exclude3 = c(18,19, 20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_fife", df = NHS24_Mon_Fri_IH_fife, place_title = "Fife", breakPoint = 26, breakPoint2 = 66, exclude3 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_forthV", df = NHS24_Mon_Fri_IH_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 33, breakPoint2 = 66, exclude3 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_gramp", df = NHS24_Mon_Fri_IH_gramp, place_title = "Grampian", exclude = 20, breakPoint = 21, breakPoint2 = 65, exclude3 = c(20,21))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_glow", df = NHS24_Mon_Fri_IH_glow, place_title = "Greater Glasgow and Clyde", exclude = 20, breakPoint = 66, exclude2 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_high", df = NHS24_Mon_Fri_IH_high, place_title = "Highlands", exclude = 20, breakPoint = 26, exclude2 = 9, breakPoint2 = 65, exclude3 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_lan", df = NHS24_Mon_Fri_IH_lan, place_title = "Lanarkshire", exclude = 20, breakPoint = 66, exclude2 = 20)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_loth", df = NHS24_Mon_Fri_IH_loth, place_title = "Lothian", exclude = 15, breakPoint = 37, breakPoint2 = 66, exclude3 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_ork", df = NHS24_Mon_Fri_IH_ork, place_title = "Orkney", exclude = 15)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_shet", df = NHS24_Mon_Fri_IH_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_tay", df = NHS24_Mon_Fri_IH_tay, place_title = "Tayside", breakPoint = 66, exclude2 = c(19,20))
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df_name = "NHS24_Mon_Fri_IH_west", df = NHS24_Mon_Fri_IH_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C'", df_name = "NHS24_Mon_Fri_IH_scot", df = NHS24_Mon_Fri_IH_scot, place_title = "Scotland", breakPoint = 34, breakPoint2 = 66, exclude3 = c(20))


plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_AA", df = NHS24_Sat_Sun_AA)
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_borders", df = NHS24_Sat_Sun_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_dg", df = NHS24_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_fife", df = NHS24_Sat_Sun_fife, place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_forthV", df = NHS24_Sat_Sun_forthV, place_title = "Forth Valley")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_gramp", df = NHS24_Sat_Sun_gramp, place_title = "Grampian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_glow", df = NHS24_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_high", df = NHS24_Sat_Sun_high, place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_lan", df = NHS24_Sat_Sun_lan, place_title = "Lanarkshire")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_loth", df = NHS24_Sat_Sun_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_ork", df = NHS24_Sat_Sun_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_shet", df = NHS24_Sat_Sun_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_tay", df = NHS24_Sat_Sun_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df_name = "NHS24_Sat_Sun_west", df = NHS24_Sat_Sun_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C'", df_name = "NHS24_Sat_Sun_scot", df = NHS24_Sat_Sun_scot, place_title = "Scotland")

#####
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_AA", df = SAS_attended_AA)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_borders", df = SAS_attended_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_dg", df = SAS_attended_dg, place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_fife", df = SAS_attended_fife, place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_forthV", df = SAS_attended_forthV, place_title = "Forth Valley")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_gramp", df = SAS_attended_gramp, place_title = "Grampian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_glow", df = SAS_attended_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_high", df = SAS_attended_high, place_title = "Highlands", breakPoint = 40)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_lan", df = SAS_attended_lan, place_title = "Lanarkshire")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_loth", df = SAS_attended_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_ork", df = SAS_attended_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_shet", df = SAS_attended_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_tay", df = SAS_attended_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df_name = "SAS_attended_west", df = SAS_attended_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Attended Incidents per Day",chart_typ = "C'", df_name = "SAS_attended_scot", df = SAS_attended_scot, place_title = "Scotland", breakPoint = 64)


plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_AA", df = SAS_conveyed_AA, breakPoint = 128)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_borders", df = SAS_conveyed_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_dg", df = SAS_conveyed_dg, place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_fife", df = SAS_conveyed_fife, place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_forthV", df = SAS_conveyed_forthV, place_title = "Forth Valley", breakPoint = 44)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_gramp", df = SAS_conveyed_gramp, place_title = "Grampian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_glow", df = SAS_conveyed_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_high", df = SAS_conveyed_high, place_title = "Highlands", breakPoint = 27)
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_lan", df = SAS_conveyed_lan, place_title = "Lanarkshire")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_loth", df = SAS_conveyed_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_ork", df = SAS_conveyed_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_shet", df = SAS_conveyed_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_tay", df = SAS_conveyed_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df_name = "SAS_conveyed_west", df = SAS_conveyed_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C'", df_name = "SAS_conveyed_scot", df = SAS_conveyed_scot, place_title = "Scotland", breakPoint = 47)


plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", df_name = "GPOOH_Mon_Fri_AA", df = GPOOH_Mon_Fri_AA)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_borders", df = GPOOH_Mon_Fri_borders, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_dg", df = GPOOH_Mon_Fri_dg, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_fife", df = GPOOH_Mon_Fri_fife, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_forthV", df = GPOOH_Mon_Fri_forthV, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Forth Valley", exclude = 5)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_gramp", df = GPOOH_Mon_Fri_gramp, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Grampian", exclude = 18)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_glow", df = GPOOH_Mon_Fri_glow, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 22, override_annotation_dist = 5)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_high", df = GPOOH_Mon_Fri_high, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_lan", df = GPOOH_Mon_Fri_lan, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lanarkshire", exclude = 18)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_loth", df = GPOOH_Mon_Fri_loth, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_ork", df = GPOOH_Mon_Fri_ork, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Orkney", exclude = 15)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_shet", df = GPOOH_Mon_Fri_shet, cht_title = "GP OOH (non-COVID) Contacts per Day",chart_typ = "C", place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_tay", df = GPOOH_Mon_Fri_tay, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Tayside", breakPoint = 22, exclude2 = 2)
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_west", df = GPOOH_Mon_Fri_west, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, df_name = "GPOOH_Mon_Fri_scot", df = GPOOH_Mon_Fri_scot, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C'", place_title = "Scotland")


plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_AA", df = GPOOH_Sat_Sun_AA)
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_borders", df = GPOOH_Sat_Sun_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_dg", df = GPOOH_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_fife", df = GPOOH_Sat_Sun_fife, place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_forthV", df = GPOOH_Sat_Sun_forthV, place_title = "Forth Valley")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_gramp", df = GPOOH_Sat_Sun_gramp, place_title = "Grampian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_glow", df = GPOOH_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_high", df = GPOOH_Sat_Sun_high, place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_lan", df = GPOOH_Sat_Sun_lan, place_title = "Lanarkshire")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_loth", df = GPOOH_Sat_Sun_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_ork", df = GPOOH_Sat_Sun_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_shet", df = GPOOH_Sat_Sun_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_tay", df = GPOOH_Sat_Sun_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df_name = "GPOOH_Sat_Sun_west", df = GPOOH_Sat_Sun_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C'", df_name = "GPOOH_Sat_Sun_scot", df = GPOOH_Sat_Sun_scot, place_title = "Scotland")


plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_AA", df = assHub_AA)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_borders", df = assHub_borders, place_title = "Borders", breakPoint = 118)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_dg", df = assHub_dg, place_title = "Dumfries and Galloway", breakPoint = 56, breakPoint2 = 116)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_fife", df = assHub_fife, place_title = "Fife", breakPoint = 22)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_forthV", df = assHub_forthV, place_title = "Forth Valley", breakPoint = 28)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_gramp", df = assHub_gramp, place_title = "Grampian", breakPoint = 117)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_glow", df = assHub_glow, place_title = "Greater Glasgow and Clyde")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_high", df = assHub_high, place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_lan", df = assHub_lan, place_title = "Lanarkshire", breakPoint = 33, breakPoint2 = 83, breakPoint3 = 117)
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_loth", df = assHub_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_ork", df = assHub_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_shet", df = assHub_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_tay", df = assHub_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df_name = "COVIDHub_west", df = assHub_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C'", df_name = "COVIDHub_scot", df = assHub_scot, place_title = "Scotland")


plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_AA", df = selfPres_AA, breakPoint = 25, breakPoint2 = 64, breakPoint3 = 86)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_borders", df = selfPres_borders, place_title = "Borders", breakPoint = 22, breakPoint2 = 85, breakPoint3 = 109)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_dg", df = selfPres_dg, place_title = "Dumfries and Galloway", breakPoint = 35, breakPoint2 = 112)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_fife", df = selfPres_fife, place_title = "Fife", breakPoint = 38, breakPoint2 = 89, breakPoint3 = 112)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_forthV", df = selfPres_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_gramp", df = selfPres_gramp, place_title = "Grampian", breakPoint = 24, breakPoint2 = 92, breakPoint3 = 127)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_glow", df = selfPres_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 43, breakPoint2 = 92, breakPoint3 = 129)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_high", df = selfPres_high, place_title = "Highlands", breakPoint = 27, breakPoint2 = 101)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_lan", df = selfPres_lan, place_title = "Lanarkshire", override_y_lim = 550, breakPoint = 37, breakPoint2 = 92, breakPoint3 = 129)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_loth", df = selfPres_loth, place_title = "Lothian", breakPoint = 39, breakPoint2 = 108)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_ork", df = selfPres_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_shet", df = selfPres_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_tay", df = selfPres_tay, place_title = "Tayside", breakPoint = 29, breakPoint2 = 94)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C", df_name = "selfPres_west", df = selfPres_west, place_title = "Western Isles", breakPoint = 75)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Self Presenters ALL per Day",chart_typ = "C'", df_name = "selfPres_scot", df = selfPres_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 92, breakPoint4 = 128)


plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_AA", df = fourHrPerf_AA, breakPoint = 31, breakPoint2 = 57)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_borders", df = fourHrPerf_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_dg", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 91)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_fife", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 56)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_forthV", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 36)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_gramp", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 87)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P'", df_name = "fourHrPerf_glow", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 35)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_high", df = fourHrPerf_high, place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_lan", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 95)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_loth", df = fourHrPerf_loth, place_title = "Lothian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_ork", df = fourHrPerf_ork, place_title = "Orkney", override_y_lim = 110)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_shet", df = fourHrPerf_shet, place_title = "Shetland", override_y_lim = 110)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_tay", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 22, override_y_lim = 110)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P", df_name = "fourHrPerf_west", df = fourHrPerf_west, place_title = "Western Isles", override_y_lim = 110)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED 4Hr Performance",chart_typ = "P'", df_name = "fourHrPerf_scot", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 35, breakPoint2 = 98)


plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_AA", df = fourHrPerf_AA, breakPoint = 24, breakPoint2 = 46, breakPoint3 = 86, breakPoint4 = 127)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_borders", df = fourHrPerf_borders, place_title = "Borders", breakPoint = 37)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_dg", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 24, breakPoint2 = 93, breakPoint3 = 118)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_fife", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 37, breakPoint2 = 67, breakPoint3 = 127)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_forthV", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_gramp", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 37, breakPoint2 = 106, breakPoint3 = 127)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_glow", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 37, breakPoint2 = 109)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_high", df = fourHrPerf_high, place_title = "Highlands", breakPoint = 36, breakPoint2 = 106)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_lan", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 37, breakPoint2 = 79)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_loth", df = fourHrPerf_loth, place_title = "Lothian", breakPoint = 43, breakPoint2 = 108)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_ork", df = fourHrPerf_ork, place_title = "Orkney", breakPoint = 99)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_shet", df = fourHrPerf_shet, place_title = "Shetland", breakPoint = 22)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_tay", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 28, breakPoint2 = 92)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C", df_name = "EDAttendances_west", df = fourHrPerf_west, place_title = "Western Isles", breakPoint = 102)
plot_SPC(plot_chart = F, write_table = T, cht_title = "ED Attendances per Day",chart_typ = "C'", df_name = "EDAttendances_scot", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 106)


plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_AA", df = emerg_ad_AA)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_borders", df = emerg_ad_borders, place_title = "Borders")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_dg", df = emerg_ad_dg, place_title = "Dumfries and Galloway")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_fife", df = emerg_ad_fife, place_title = "Fife")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_forthV", df = emerg_ad_forthV, place_title = "Forth Valley")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_gramp", df = emerg_ad_gramp, place_title = "Grampian")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_glow", df = emerg_ad_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 54)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_high", df = emerg_ad_high, place_title = "Highlands")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_lan", df = emerg_ad_lan, place_title = "Lanarkshire", breakPoint = 93)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_loth", df = emerg_ad_loth, place_title = "Lothian", breakPoint = 92)
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_ork", df = emerg_ad_ork, place_title = "Orkney")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_shet", df = emerg_ad_shet, place_title = "Shetland")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_tay", df = emerg_ad_tay, place_title = "Tayside")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C", df_name = "emerg_ad_west", df = emerg_ad_west, place_title = "Western Isles")
plot_SPC(plot_chart = F, write_table = T, cht_title = "Emergency Admissions per Day",chart_typ = "C'", df_name = "emerg_ad_scot", df = emerg_ad_scot, place_title = "Scotland", breakPoint = 88)