#script for graphs

plot_volume_recalc_three_breakpoints(df = NHS24_Mon_Fri_AA, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", breakPoint = 43)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_borders, place_title = "Borders",breakPoint = 64)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_dg, place_title = "Dumfries and Galloway", breakPoint = 73)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_fife, place_title = "Fife", breakPoint = 64)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 29, breakPoint2 = 66, exclude3 = c(18,22))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_gramp, place_title = "Grampian", exclude = 18, breakPoint = 64, exclude2 = 19)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_glow, place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_high, place_title = "Highlands", breakPoint = 25, exclude2 = 8, breakPoint2 = 64, exclude3 = 19)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_lan, place_title = "Lanarkshire", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_loth, place_title = "Lothian", breakPoint = 27, breakPoint2 = 64, exclude3 = 19)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_ork, place_title = "Orkney", exclude = 18, breakPoint = 40)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_tay, place_title = "Tayside", breakPoint = 64, exclude2 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_west, place_title = "Western Isles", breakPoint = 64, exclude2 = 20)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C'", df = NHS24_Mon_Fri_scot, place_title = "Scotland", breakPoint = 32, breakPoint2 = 64, exclude3 = 20)


plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_AA, exclude = c(14,15), breakPoint = 45)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_borders,place_title = "Borders", breakPoint = 66)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_dg,place_title = "Dumfries and Galloway", breakPoint = 33, breakPoint2 = 66, exclude3 = c(18,19, 20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_fife, place_title = "Fife", breakPoint = 26, breakPoint2 = 66, exclude3 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 33, breakPoint2 = 66, exclude3 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_gramp, place_title = "Grampian", exclude = 20, breakPoint = 21, breakPoint2 = 65, exclude3 = c(20,21))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_glow, place_title = "Greater Glasgow and Clyde", exclude = 20, breakPoint = 66, exclude2 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_high, place_title = "Highlands", exclude = 20, breakPoint = 26, exclude2 = 9, breakPoint2 = 65, exclude3 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_lan, place_title = "Lanarkshire", exclude = 20, breakPoint = 66, exclude2 = 20)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_loth, place_title = "Lothian", exclude = 15, breakPoint = 37, breakPoint2 = 66, exclude3 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_ork, place_title = "Orkney", exclude = 15)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_tay, place_title = "Tayside", breakPoint = 66, exclude2 = c(19,20))
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C'", df = NHS24_Mon_Fri_IH_scot, place_title = "Scotland", breakPoint = 34, breakPoint2 = 66, exclude3 = c(20))


plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_AA)
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_fife, place_title = "Fife")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_forthV, place_title = "Forth Valley")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_gramp, place_title = "Grampian")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_high, place_title = "Highlands")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_lan, place_title = "Lanarkshire")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24  Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_tay, place_title = "Tayside")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C'", df = NHS24_Sat_Sun_scot, place_title = "Scotland")


plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_AA)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_dg, place_title = "Dumfries and Galloway")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_fife, place_title = "Fife")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_forthV, place_title = "Forth Valley")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_gramp, place_title = "Grampian")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_high, place_title = "Highlands", breakPoint = 40)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_lan, place_title = "Lanarkshire")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_tay, place_title = "Tayside")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Attended Incidents per Day",chart_typ = "C'", df = SAS_attended_scot, place_title = "Scotland", breakPoint = 64)


plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_AA)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_dg, place_title = "Dumfries and Galloway")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_fife, place_title = "Fife")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_forthV, place_title = "Forth Valley", breakPoint = 44)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_gramp, place_title = "Grampian")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_high, place_title = "Highlands", breakPoint = 27)
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_lan, place_title = "Lanarkshire")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_tay, place_title = "Tayside")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C'", df = SAS_conveyed_scot, place_title = "Scotland", breakPoint = 47)


plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", df = GPOOH_Mon_Fri_AA)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_borders, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Borders")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_dg, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Dumfries and Galloway")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_fife, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Fife")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_forthV, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Forth Valley", exclude = 5)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_gramp, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Grampian", exclude = 18)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_glow, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 22, override_annotation_dist = 5)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_high, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Highlands")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_lan, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lanarkshire", exclude = 18)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_loth, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lothian")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_ork, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Orkney", exclude = 15)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_shet, cht_title = "GP OOH (non-COVID) Contacts per Day",chart_typ = "C", place_title = "Shetland")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_tay, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Tayside", breakPoint = 22, exclude2 = 2)
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_west, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(df = GPOOH_Mon_Fri_scot, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C'", place_title = "Scotland")


plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_AA)
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_fife, place_title = "Fife")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_forthV, place_title = "Forth Valley")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_gramp, place_title = "Grampian")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_high, place_title = "Highlands")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_lan, place_title = "Lanarkshire")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_tay, place_title = "Tayside")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C'", df = GPOOH_Sat_Sun_scot, place_title = "Scotland")


plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_AA)
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_dg, place_title = "Dumfries and Galloway", breakPoint = 56, breakPoint2 = 116)
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_fife, place_title = "Fife", breakPoint = 22)
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_forthV, place_title = "Forth Valley", breakPoint = 28)
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_gramp, place_title = "Grampian", breakPoint = 117)
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_glow, place_title = "Greater Glasgow and Clyde")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_high, place_title = "Highlands")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_lan, place_title = "Lanarkshire")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_tay, place_title = "Tayside")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_west, place_title = "Western Isles")
plot_volume_recalc_three_breakpoints(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C'", df = assHub_scot, place_title = "Scotland")


plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_AA, breakPoint = 25, breakPoint2 = 64, breakPoint3 = 86)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_borders, place_title = "Borders", breakPoint = 22, breakPoint2 = 85)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_dg, place_title = "Dumfries and Galloway", breakPoint = 35)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_fife, place_title = "Fife", breakPoint = 38, breakPoint2 = 89, breakPoint3 = 112)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_gramp, place_title = "Grampian", breakPoint = 24, breakPoint2 = 92)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 43, breakPoint2 = 92)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_high, place_title = "Highlands", breakPoint = 27, breakPoint2 = 101)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_lan, place_title = "Lanarkshire", override_y_lim = 550, breakPoint = 37, breakPoint2 = 92)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_loth, place_title = "Lothian", breakPoint = 39)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_ork, place_title = "Orkney")
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_shet, place_title = "Shetland")
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_tay, place_title = "Tayside", breakPoint = 29, breakPoint2 = 94)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_west, place_title = "Western Isles", breakPoint = 75)
plot_volume_recalc_three_breakpoints(cht_title = "Self Presenters ALL per Day",chart_typ = "C'", df = selfPres_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 92)


plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_AA, breakPoint = 31, breakPoint2 = 57)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_borders, place_title = "Borders")
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 91)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 56)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 36)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 87)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P'", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 35)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_high, place_title = "Highlands")
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 95)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_loth, place_title = "Lothian")
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_ork, place_title = "Orkney", override_y_lim = 110)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_shet, place_title = "Shetland", override_y_lim = 110)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 22, override_y_lim = 110)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_west, place_title = "Western Isles", override_y_lim = 110)
plot_volume_recalc_three_breakpoints(cht_title = "ED 4Hr Performance",chart_typ = "P'", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 35, breakPoint2 = 98)


plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_AA, breakPoint = 24, breakPoint2 = 46, breakPoint3 = 86)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_borders, place_title = "Borders", breakPoint = 37)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 24, breakPoint2 = 93)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 37, breakPoint2 = 67)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 37, breakPoint2 = 106)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 37, breakPoint2 = 109)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_high, place_title = "Highlands", breakPoint = 36, breakPoint2 = 106)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 37, breakPoint2 = 79)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_loth, place_title = "Lothian", breakPoint = 43)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_ork, place_title = "Orkney", breakPoint = 99)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_shet, place_title = "Shetland", breakPoint = 22)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 28, breakPoint2 = 92)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_west, place_title = "Western Isles", breakPoint = 102)
plot_volume_recalc_three_breakpoints(cht_title = "ED Attendances per Day",chart_typ = "C'", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 106)