#script for graphs

plot_SPC(df = NHS24_Mon_Fri_AA, cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", place_title = "Ayrshire and Arran", breakPoint = 43, breakPoint2 = 104)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_borders, place_title = "Borders",breakPoint = 64, breakPoint2 = 104)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_dg, place_title = "Dumfries and Galloway", breakPoint = 73, exclude2 = c(11,15,16))
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_fife, place_title = "Fife", breakPoint = 64, exclude2 = 20, breakPoint2 = 94)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 29, breakPoint2 = 66, exclude3 = c(18,22), breakPoint3 = 89)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_gramp, place_title = "Grampian", exclude = 18, breakPoint = 64, exclude2 = 19, breakPoint2 = 105)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_glow, place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_high, place_title = "Highlands", breakPoint = 25, exclude2 = 8, breakPoint2 = 64, exclude3 = 19)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_lan, place_title = "Lanarkshire", exclude = 18, breakPoint = 64, exclude2 = 20)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_loth, place_title = "Lothian", breakPoint = 27, breakPoint2 = 64, exclude3 = 19, breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_ork, place_title = "Orkney", exclude = 18, breakPoint = 40)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_shet, place_title = "Shetland")
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_tay, place_title = "Tayside", breakPoint = 64, exclude2 = c(19,20), breakPoint2 = 107)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_west, place_title = "Western Isles", breakPoint = 64, exclude2 = 20)
plot_SPC(cht_title = "NHS 24 Mon-Fri: ALL Contacts per Day",chart_typ = "C'", df = NHS24_Mon_Fri_scot, place_title = "Scotland", breakPoint = 32, breakPoint2 = 64, exclude3 = 20)


plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_AA, exclude = c(14,15), place_title = "Ayrshire and Arran", breakPoint = 45, breakPoint2 = 109)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_borders,place_title = "Borders", breakPoint = 66, breakPoint2 = 106)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_dg,place_title = "Dumfries and Galloway", breakPoint = 33, breakPoint2 = 66, exclude3 = c(18,19, 20), breakPoint3 = 92)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_fife, place_title = "Fife", breakPoint = 26, breakPoint2 = 66, exclude3 = c(19,20), breakPoint3 = 108)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_forthV, place_title = "Forth Valley", exclude = 5, breakPoint = 33, breakPoint2 = 66, exclude3 = c(19,20), breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_gramp, place_title = "Grampian", exclude = 20, breakPoint = 21, breakPoint2 = 65, exclude3 = c(20,21), breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_glow, place_title = "Greater Glasgow and Clyde", exclude = 20, breakPoint = 66, exclude2 = c(19,20), breakPoint2 = 88, exclude3 = c(2,3), breakPoint3 = 111)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_high, place_title = "Highlands", exclude = 20, breakPoint = 26, exclude2 = 9, breakPoint2 = 65, exclude3 = c(19,20))
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_lan, place_title = "Lanarkshire", exclude = 20, breakPoint = 66, exclude2 = 20)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_loth, place_title = "Lothian", exclude = 15, breakPoint = 37, breakPoint2 = 66, exclude3 = c(19,20))
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_ork, place_title = "Orkney", exclude = 15)
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_shet, place_title = "Shetland")
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_tay, place_title = "Tayside", breakPoint = 66, exclude2 = c(19,20))
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C", df = NHS24_Mon_Fri_IH_west, place_title = "Western Isles")
plot_SPC(cht_title = "NHS 24 Mon-Fri: In Hours Contacts per Day",chart_typ = "C'", df = NHS24_Mon_Fri_IH_scot, place_title = "Scotland", breakPoint = 34, breakPoint2 = 66, exclude3 = c(20), breakPoint3 = 87, exclude4 = c(4,5), breakPoint4 = 108)


plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_AA, place_title = "Ayrshire and Arran", breakPoint = 36)
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_borders, place_title = "Borders")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_fife, place_title = "Fife")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_forthV, place_title = "Forth Valley")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_gramp, place_title = "Grampian")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_high, place_title = "Highlands")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_lan, place_title = "Lanarkshire")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_loth, place_title = "Lothian")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_ork, place_title = "Orkney")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_shet, place_title = "Shetland")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_tay, place_title = "Tayside")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C", df = NHS24_Sat_Sun_west, place_title = "Western Isles")
plot_SPC(cht_title = "NHS 24 Sat-Sun Contacts per Day",chart_typ = "C'", df = NHS24_Sat_Sun_scot, place_title = "Scotland")


plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_AA, place_title = "Ayrshire and Arran", breakPoint = 142)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_borders, place_title = "Borders")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_dg, place_title = "Dumfries and Galloway")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_fife, place_title = "Fife", breakPoint = 147)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_forthV, place_title = "Forth Valley")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_gramp, place_title = "Grampian")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_high, place_title = "Highlands", breakPoint = 40)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_lan, place_title = "Lanarkshire")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_loth, place_title = "Lothian", breakPoint = 95)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_ork, place_title = "Orkney")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_shet, place_title = "Shetland")
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_tay, place_title = "Tayside", breakPoint = 107)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C", df = SAS_attended_west, place_title = "Western Isles", breakPoint = 96)
plot_SPC(cht_title = "SAS Attended Incidents per Day",chart_typ = "C'", df = SAS_attended_scot, place_title = "Scotland", breakPoint = 64)


plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_AA, place_title = "Ayrshire and Arran", breakPoint = 128)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_borders, place_title = "Borders")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_dg, place_title = "Dumfries and Galloway")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_fife, place_title = "Fife")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_forthV, place_title = "Forth Valley", breakPoint = 44)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_gramp, place_title = "Grampian")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 89)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_high, place_title = "Highlands", breakPoint = 27, breakPoint2 = 113)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_lan, place_title = "Lanarkshire", breakPoint = 100)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_loth, place_title = "Lothian", breakPoint = 100)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_ork, place_title = "Orkney")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_shet, place_title = "Shetland")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_tay, place_title = "Tayside", breakPoint = 107)
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C", df = SAS_conveyed_west, place_title = "Western Isles")
plot_SPC(cht_title = "SAS Conveyed Incidents per Day",chart_typ = "C'", df = SAS_conveyed_scot, place_title = "Scotland", breakPoint = 47)


plot_SPC(cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", df = GPOOH_Mon_Fri_AA, place_title = "Ayrshire and Arran", breakPoint = 93)
plot_SPC(df = GPOOH_Mon_Fri_borders, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Borders")
plot_SPC(df = GPOOH_Mon_Fri_dg, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Dumfries and Galloway", breakPoint = 76, exclude2 = c(8,12,13))
plot_SPC(df = GPOOH_Mon_Fri_fife, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Fife")
plot_SPC(df = GPOOH_Mon_Fri_forthV, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Forth Valley", exclude = 5, breakPoint = 39)
plot_SPC(df = GPOOH_Mon_Fri_gramp, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Grampian", exclude = 18)
plot_SPC(df = GPOOH_Mon_Fri_glow, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Greater Glasgow and Clyde", exclude = 18, breakPoint = 22, override_annotation_dist = 5)
plot_SPC(df = GPOOH_Mon_Fri_high, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Highlands")
plot_SPC(df = GPOOH_Mon_Fri_lan, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lanarkshire", exclude = 18)
plot_SPC(df = GPOOH_Mon_Fri_loth, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Lothian", breakPoint = 60)
plot_SPC(df = GPOOH_Mon_Fri_ork, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Orkney", exclude = 15)
plot_SPC(df = GPOOH_Mon_Fri_shet, cht_title = "GP OOH (non-COVID) Contacts per Day",chart_typ = "C", place_title = "Shetland")
plot_SPC(df = GPOOH_Mon_Fri_tay, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Tayside", breakPoint = 22, exclude2 = 2, breakPoint2 = 94)
plot_SPC(df = GPOOH_Mon_Fri_west, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C", place_title = "Western Isles", breakPoint = 31)
plot_SPC(df = GPOOH_Mon_Fri_scot, cht_title = "GP OOH (non-COVID): Mon-Fri Contacts per Day",chart_typ = "C'", place_title = "Scotland")


plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_AA,place_title = "Ayrshire and Arran", )
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_borders, place_title = "Borders")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_dg, place_title = "Dumfries and Galloway")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_fife, place_title = "Fife")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_forthV, place_title = "Forth Valley")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_gramp, place_title = "Grampian")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_glow, place_title = "Greater Glasgow and Clyde")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_high, place_title = "Highlands")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_lan, place_title = "Lanarkshire")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_loth, place_title = "Lothian")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_ork, place_title = "Orkney")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_shet, place_title = "Shetland")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_tay, place_title = "Tayside")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C", df = GPOOH_Sat_Sun_west, place_title = "Western Isles")
plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Contacts per Day",chart_typ = "C'", df = GPOOH_Sat_Sun_scot, place_title = "Scotland")


plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_AA, place_title = "Ayrshire and Arran", breakPoint = 36, breakPoint2 = 123, breakPoint3 = 149)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_borders, place_title = "Borders", breakPoint = 118, breakPoint2 = 143)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_dg, place_title = "Dumfries and Galloway", breakPoint = 56, breakPoint2 = 116, breakPoint3 = 146)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_fife, place_title = "Fife", breakPoint = 22, breakPoint2 = 154)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_forthV, place_title = "Forth Valley", breakPoint = 28)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_gramp, place_title = "Grampian", breakPoint = 117, breakPoint2 = 137, breakPoint3 = 158)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 160)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_high, place_title = "Highlands")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_lan, place_title = "Lanarkshire", breakPoint = 33, breakPoint2 = 83, breakPoint3 = 117, breakPoint4 = 148)
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_loth, place_title = "Lothian")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_ork, place_title = "Orkney")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_shet, place_title = "Shetland")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_tay, place_title = "Tayside")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C", df = assHub_west, place_title = "Western Isles")
plot_SPC(cht_title = "COVID Hub and Assessment Centre Contacts per Day",chart_typ = "C'", df = assHub_scot, place_title = "Scotland")


plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_AA, place_title = "Ayrshire and Arran", breakPoint = 25, breakPoint2 = 64, breakPoint3 = 86, breakPoint4 = 132)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_borders, place_title = "Borders", breakPoint = 22, breakPoint2 = 85, breakPoint3 = 109)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_dg, place_title = "Dumfries and Galloway", breakPoint = 35, breakPoint2 = 112, breakPoint3 = 133)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_fife, place_title = "Fife", breakPoint = 38, breakPoint2 = 89, breakPoint3 = 112, breakPoint4 = 133)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_gramp, place_title = "Grampian", breakPoint = 24, breakPoint2 = 92, breakPoint3 = 127, breakPoint4 = 158)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 43, breakPoint2 = 92, breakPoint3 = 129)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_high, place_title = "Highlands", breakPoint = 27, breakPoint2 = 101, breakPoint3 = 134)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_lan, place_title = "Lanarkshire", override_y_lim = 550, breakPoint = 37, breakPoint2 = 92, breakPoint3 = 129)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_loth, place_title = "Lothian", breakPoint = 39, breakPoint2 = 108, breakPoint3 = 130)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_ork, place_title = "Orkney", breakPoint = 124)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_shet, place_title = "Shetland", breakPoint = 113)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_tay, place_title = "Tayside", breakPoint = 29, breakPoint2 = 94, breakPoint3 = 131)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C", df = selfPres_west, place_title = "Western Isles", breakPoint = 75)
plot_SPC(cht_title = "Self Presenters ALL per Day",chart_typ = "C'", df = selfPres_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 92, breakPoint4 = 128)


plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_AA, place_title = "Ayrshire and Arran", breakPoint = 31, breakPoint2 = 57)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_borders, place_title = "Borders", breakPoint = 150)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 91)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 56)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 36, breakPoint2 = 102)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 87, breakPoint2 = 127, breakPoint3 = 153)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P'", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 35)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_high, place_title = "Highlands")
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 95, breakPoint2 = 142)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_loth, place_title = "Lothian", breakPoint = 151)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_ork, place_title = "Orkney", override_y_lim = 110)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_shet, place_title = "Shetland", override_y_lim = 110)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 22, override_y_lim = 110)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P", df = fourHrPerf_west, place_title = "Western Isles", override_y_lim = 110)
plot_SPC(cht_title = "ED 4Hr Performance",chart_typ = "P'", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 35, breakPoint2 = 98)


plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_AA, place_title = "Ayrshire and Arran", breakPoint = 24, breakPoint2 = 46, breakPoint3 = 86, breakPoint4 = 127)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_borders, place_title = "Borders", breakPoint = 37)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_dg, place_title = "Dumfries and Galloway", breakPoint = 24, breakPoint2 = 93, breakPoint3 = 118)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_fife, place_title = "Fife", breakPoint = 37, breakPoint2 = 67, breakPoint3 = 127)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_forthV, place_title = "Forth Valley", breakPoint = 22, breakPoint2 = 99)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_gramp, place_title = "Grampian", breakPoint = 37, breakPoint2 = 106, breakPoint3 = 127)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 37, breakPoint2 = 109, breakPoint3 = 130, breakPoint4 = 161)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_high, place_title = "Highlands", breakPoint = 36, breakPoint2 = 106)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_lan, place_title = "Lanarkshire", breakPoint = 37, breakPoint2 = 79)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_loth, place_title = "Lothian", breakPoint = 43, breakPoint2 = 108, breakPoint3 = 129)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_ork, place_title = "Orkney", breakPoint = 99)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_shet, place_title = "Shetland", breakPoint = 22)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_tay, place_title = "Tayside", breakPoint = 28, breakPoint2 = 92)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C", df = fourHrPerf_west, place_title = "Western Isles", breakPoint = 102)
plot_SPC(cht_title = "ED Attendances per Day",chart_typ = "C'", df = fourHrPerf_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 43, breakPoint3 = 106)


plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_AA, place_title = "Ayrshire and Arran", breakPoint = 108)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_borders, place_title = "Borders")
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_dg, place_title = "Dumfries and Galloway", breakPoint = 155)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_fife, place_title = "Fife")
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_forthV, place_title = "Forth Valley", breakPoint = 121)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_gramp, place_title = "Grampian")
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 54)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_high, place_title = "Highlands")
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_lan, place_title = "Lanarkshire", breakPoint = 93)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_loth, place_title = "Lothian", breakPoint = 92)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_ork, place_title = "Orkney", breakPoint = 40)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_shet, place_title = "Shetland", breakPoint = 34)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_tay, place_title = "Tayside", breakPoint = 147)
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C", df = emerg_ad_west, place_title = "Western Isles")
plot_SPC(cht_title = "Emergency Admissions per Day",chart_typ = "C'", df = emerg_ad_scot, place_title = "Scotland", breakPoint = 88)


plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_AA, place_title = "Ayrshire and Arran", breakPoint = 62)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_borders, place_title = "Borders", breakPoint = 41)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_dg, place_title = "Dumfries and Galloway", breakPoint = 89)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_fife, place_title = "Fife")
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_forthV, place_title = "Forth Valley")
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_gramp, place_title = "Grampian", breakPoint = 26)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 28, breakPoint2 = 72)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_high, place_title = "Highlands")
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_lan, place_title = "Lanarkshire", breakPoint = 42, breakPoint2 = 94)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_loth, place_title = "Lothian", breakPoint = 56)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_ork, place_title = "Orkney", breakPoint = 62)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_shet, place_title = "Shetland", breakPoint = 24)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_tay, place_title = "Tayside", breakPoint = 95)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C", df = emerg_ad_weekday_west, place_title = "Western Isles", breakPoint = 26, breakPoint2 = 57)
plot_SPC(cht_title = "Emergency Admissions: Mon-Fri per Day",chart_typ = "C'", df = emerg_ad_weekday_scot, place_title = "Scotland", breakPoint = 22, breakPoint2 = 62, breakPoint3 = 96)

plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_AA, place_title = "Ayrshire and Arran", )
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_borders, place_title = "Borders")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_dg, place_title = "Dumfries and Galloway")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_fife, place_title = "Fife")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_forthV, place_title = "Forth Valley")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_gramp, place_title = "Grampian")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_glow, place_title = "Greater Glasgow and Clyde", breakPoint = 22)
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_high, place_title = "Highlands")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_lan, place_title = "Lanarkshire - data up to 22/02/21")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_loth, place_title = "Lothian", breakPoint = 24)
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_ork, place_title = "Orkney")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_shet, place_title = "Shetland")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_tay, place_title = "Tayside")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C", df = emerg_ad_weekend_west, place_title = "Western Isles")
plot_SPC(cht_title = "Emergency Admissions: Sat-Sun per Day",chart_typ = "C'", df = emerg_ad_weekend_scot, place_title = "Scotland - Using estimated values for Lanarkshire from 23/02/21 onwards")


#Paediatrics
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_under_1_weekday, place_title = "Age: Under 1", breakPoint = 39, breakPoint2 = 92)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_under_12_weekday, place_title = "Age: Under 12", breakPoint = 22, breakPoint2 = 57, breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_1_4_weekday, place_title = "Age: 1-4", breakPoint = 70, breakPoint2 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_5_9_weekday, place_title = "Age: 5-9", breakPoint = 26, breakPoint2 = 66, breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_10_14_weekday, place_title = "Age: 10-14", breakPoint = 22, breakPoint2 = 51, breakPoint3 = 91)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_15_19_weekday, place_title = "Age: 15-19", breakPoint = 26, breakPoint2 = 66, breakPoint3 = 96)


plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_under_1_weekend, place_title = "Age: Under 1", breakPoint = 31)
plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_under_12_weekend, place_title = "Age: Under 12", breakPoint = 33)
plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_1_4_weekend, place_title = "Age: 1-4", breakPoint = 35)
plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_5_9_weekend, place_title = "Age: 5-9")
plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_10_14_weekend, place_title = "Age: 10-14", breakPoint = 31)
plot_SPC(cht_title = "NHS 24 Sat-Sun: Paediatric Contacts per Day",chart_typ = "C", df = NHS24_15_19_weekend, place_title = "Age: 15-19", breakPoint = 27)


plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_under_1, place_title = "Age: Under 1", breakPoint = 110)
plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_under_12, place_title = "Age: Under 12", breakPoint = 38, breakPoint2 = 109)
plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_1_4, place_title = "Age: 1-4", breakPoint = 42, breakPoint2 = 113)
plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_5_9, place_title = "Age: 5-9", breakPoint = 39, breakPoint2 = 113)
plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_10_14, place_title = "Age: 10-14", breakPoint = 39, breakPoint2 = 109)
plot_SPC(cht_title = "Paediatric ED Attendances per Day",chart_typ = "C", df = ED_attendances_15_19, place_title = "Age: 15-19")


plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_under_1, place_title = "Age: Under 1", breakPoint = 109)
plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_under_12, place_title = "Age: Under 12", breakPoint = 113, breakPoint2 = 147)
plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_1_4, place_title = "Age: 1-4", breakPoint = 22, breakPoint2 = 113)
plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_5_9, place_title = "Age: 5-9", breakPoint = 119)
plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_10_14, place_title = "Age: 10-14", breakPoint = 45, breakPoint2 = 112)
plot_SPC(cht_title = "SAS Attended Incidents: Paediatrics per Day",chart_typ = "C", df = SAS_paediatrics_15_19, place_title = "Age: 15-19", breakPoint = 126)


#Mental Health
plot_SPC(cht_title = "GP OOH (non-COVID): Mon-Fri Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland",df = GPOOH_MH_weekday)

plot_SPC(cht_title = "GP OOH (non-COVID): Sat-Sun Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland",df = GPOOH_MH_weekend)


plot_SPC(cht_title = "NHS 24 Mon-Fri: Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland (PWP and Symptoms)",df = NHS24_MH_PWP_Symptoms_weekday, breakPoint = 90)
plot_SPC(cht_title = "NHS 24 Mon-Fri: Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland (PWP only)",df = NHS24_MH_PWP_only_weekday, breakPoint = 91)

plot_SPC(cht_title = "NHS 24 Sat-Sun: Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland (PWP and Symptoms)",df = NHS24_MH_PWP_Symptoms_weekend)
plot_SPC(cht_title = "NHS 24 Sat-Sun: Mental Health Contacts per Day",chart_typ = "C'", place_title = "Scotland (PWP only)",df = NHS24_MH_PWP_only_weekend)

plot_SPC(cht_title = "Mental Health ED Attendances per Day",chart_typ = "C", df = ED_attendances_MH, place_title = "Scotland")

plot_SPC(cht_title = "SAS Attended Incidents: Mental Health per Day",chart_typ = "C", df = SAS_MH, place_title = "Scotland")

